name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
	
    # 변경 사항 : 
    # name: docker login 추가
    # name: Build the Docker image 수정
    # name: docker push 추가
    
    steps:
    - uses: actions/checkout@v4
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: docker build --tag ${{secrets.DOCKER_USER}}/hangman:latest .
    
    - name : docker push
      run : docker push ${{secrets.DOCKER_USER}}/hangman:latest
